/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 766c82fd489601c74520608d96243e63)
interface __BaseEnv_Env {
	PMGS_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	CURRENT_RELEASE: "JPPM2026002";
	RELEASE_CATALOG_JSON: "{\"JPPM2026002\":{\"ipc_edition\":\"8U\"}}";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CURRENT_RELEASE" | "RELEASE_CATALOG_JSON">> {}
}
